### ISSUE TITLE
unknown network kickstart URL $kickstart

### ISSUE THREAD

**Issue by zhouzhuoCSUFT** [ubccr/grendel#15]
Hi, When I use the latest version of grendel, I will report the following error

```bash
# ./grendel --verbose serve -c /usr/share/grendel/etc/grendel.toml --hosts /usr/share/grendel/etc/hosts.json --images /usr/share/grendel/etc/images.json
```
![image](https://user-images.githubusercontent.com/37490415/198856920-7742a8a0-741e-4e6b-bb2d-a5d451d2f768.png)

But I use the old version before, this step is normal
```bash
# ./grendel.bak --verbose serve -c /usr/share/grendel/etc/grendel.toml --hosts /usr/share/grendel/etc/hosts.json --images /usr/share/grendel/etc/images.json
```
![image](https://user-images.githubusercontent.com/37490415/198856983-1a78425b-fd6a-430f-a688-978051537aa4.png)

How to deal with this problem? 
some info :
```bash
[root@node01 bin]# md5sum grendel 
e7fb63985e795c5a9d6ccc57d5dfc841  grendel
[root@node01 bin]# md5sum grendel.bak 
14f6727929f1854802b284249e80ffef  grendel.bak

[root@node01 bin]# cat /usr/share/grendel/etc/images.json 
[
 {
    "name": "test_node",
    "kernel": "/var/lib/grendel/repo/isolinux/vmlinuz",
    "initrd": [
        "/var/lib/grendel/repo/isolinux/initrd.img"
    ],
    "provision_template": "test_node.ks.tmpl",
    "cmdline": "ks=$kickstart network ksdevice=bootif ks.device=bootif inst.sshd"
  }
]



```

**Comment by aebruno** [comment]
@zhouzhuoCSUFT Thanks for submitting this issue. The latest version of grendel changed the way the `cmdline` is processed to use go templates. Try this new syntax instead:

```
"cmdline": "ks={{ $.kickstart }} network ksdevice=bootif ks.device=bootif inst.sshd"
```

We'll make a note of this in the docs to better alter users to this change.

**Comment by zhouzhuoCSUFT** [comment]
thanks ,it works!
